#!/bin/bash

# Fail script if any command fails to execute
set -e

# Ignore any unchecked file
echo "Stashing changes before doing checks"
git stash push -q -u --keep-index

# Pop the stash once the scripts finishes, fails or gets cancelled
function pop_stash() {
    echo "Checks completed, popping stash"
    git stash pop -q
}

trap "exit" INT TERM ERR
trap pop_stash EXIT

# Do the actual check ups
./gradlew ktlintCheck detekt
