/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class realmcJNI {
  public final static native long realm_config_new();
  public final static native boolean realm_config_set_path(long jarg1, String jarg2);
  public final static native long realm_open(long jarg1);
  public final static native boolean realm_close(long jarg1);
  public final static native void custom(String jarg1);
}
