/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


import io.realm.LongPointerWrapper;

public class realmc {

  // > Manual additions
  // < Manual addition

  public static long realm_config_new() {
    return realmcJNI.realm_config_new();
}

  public static boolean realm_config_set_path(long arg0, String arg1) {
    return realmcJNI.realm_config_set_path(arg0, arg1);
  }

  public static LongPointerWrapper realm_open(long config) {
    return new LongPointerWrapper(realmcJNI.realm_open(config));
}

  public static boolean realm_close(LongPointerWrapper arg0) {
    return realmcJNI.realm_close(arg0.get());
  }

  public static void custom(String s) {
    realmcJNI.custom(s);
  }

}
