/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class realm_value_type_e {
  public final static realm_value_type_e RLM_TYPE_NULL = new realm_value_type_e("RLM_TYPE_NULL");
  public final static realm_value_type_e RLM_TYPE_INT = new realm_value_type_e("RLM_TYPE_INT");
  public final static realm_value_type_e RLM_TYPE_BOOL = new realm_value_type_e("RLM_TYPE_BOOL");
  public final static realm_value_type_e RLM_TYPE_STRING = new realm_value_type_e("RLM_TYPE_STRING");
  public final static realm_value_type_e RLM_TYPE_BINARY = new realm_value_type_e("RLM_TYPE_BINARY");
  public final static realm_value_type_e RLM_TYPE_TIMESTAMP = new realm_value_type_e("RLM_TYPE_TIMESTAMP");
  public final static realm_value_type_e RLM_TYPE_FLOAT = new realm_value_type_e("RLM_TYPE_FLOAT");
  public final static realm_value_type_e RLM_TYPE_DOUBLE = new realm_value_type_e("RLM_TYPE_DOUBLE");
  public final static realm_value_type_e RLM_TYPE_DECIMAL128 = new realm_value_type_e("RLM_TYPE_DECIMAL128");
  public final static realm_value_type_e RLM_TYPE_OBJECT_ID = new realm_value_type_e("RLM_TYPE_OBJECT_ID");
  public final static realm_value_type_e RLM_TYPE_LINK = new realm_value_type_e("RLM_TYPE_LINK");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static realm_value_type_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + realm_value_type_e.class + " with value " + swigValue);
  }

  private realm_value_type_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private realm_value_type_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private realm_value_type_e(String swigName, realm_value_type_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static realm_value_type_e[] swigValues = { RLM_TYPE_NULL, RLM_TYPE_INT, RLM_TYPE_BOOL, RLM_TYPE_STRING, RLM_TYPE_BINARY, RLM_TYPE_TIMESTAMP, RLM_TYPE_FLOAT, RLM_TYPE_DOUBLE, RLM_TYPE_DECIMAL128, RLM_TYPE_OBJECT_ID, RLM_TYPE_LINK };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

