/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_CInterop */

#ifndef _Included_io_realm_CInterop
#define _Included_io_realm_CInterop
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jlong JNICALL Java_io_realm_CInterop_JNI_1initTmpDir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_realm_CInterop
 * Method:    JNI_openRealm
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_CInterop_JNI_1openRealm
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     io_realm_CInterop
 * Method:    JNI_addObject
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_CInterop_JNI_1addObject
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_realm_CInterop
 * Method:    JNI_beginTransaction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_CInterop_JNI_1beginTransaction
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_CInterop
 * Method:    JNI_commitTransaction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_CInterop_JNI_1commitTransaction
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_CInterop
 * Method:    JNI_cancelTransaction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_CInterop_JNI_1cancelTransaction
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_CInterop
 * Method:    JNI_realmresultsQuery
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_CInterop_JNI_1realmresultsQuery
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     io_realm_CInterop
 * Method:    JNI_objectGetString
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_CInterop_JNI_1objectGetString
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_realm_CInterop
 * Method:    JNI_objectSetString
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_CInterop_JNI_1objectSetString
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     io_realm_CInterop
 * Method:    JNI_objectGetInt64
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_CInterop_JNI_1objectGetInt64
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_realm_CInterop
 * Method:    JNI_objectSetInt64
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_io_realm_CInterop_JNI_1objectSetInt64
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     io_realm_CInterop
 * Method:    JNI_queryGetSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_CInterop_JNI_1queryGetSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_CInterop
 * Method:    JNI_queryGetObjectAt
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_CInterop_JNI_1queryGetObjectAt
  (JNIEnv *, jobject, jlong, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
