blank_issues_enabled: true
contact_links:
  - name: General Questions and Inquiries
    url: https://www.mongodb.com/community/forums/tags/c/atlas-app-services-realm/9/kotlin
    about: Please ask general design/architecture questions in the community forums.
  - name: MongoDB Atlas Device Sync Production Issues
    url: https://support.mongodb.com/
    about: Please report urgent production issues to the support portal directly.
