/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class realm_query_cond_e {
  public final static realm_query_cond_e RLM_QUERY_EQUAL = new realm_query_cond_e("RLM_QUERY_EQUAL");
  public final static realm_query_cond_e RLM_QUERY_NOT_EQUAL = new realm_query_cond_e("RLM_QUERY_NOT_EQUAL");
  public final static realm_query_cond_e RLM_QUERY_GREATER = new realm_query_cond_e("RLM_QUERY_GREATER");
  public final static realm_query_cond_e RLM_QUERY_GREATER_EQUAL = new realm_query_cond_e("RLM_QUERY_GREATER_EQUAL");
  public final static realm_query_cond_e RLM_QUERY_LESS = new realm_query_cond_e("RLM_QUERY_LESS");
  public final static realm_query_cond_e RLM_QUERY_LESS_EQUAL = new realm_query_cond_e("RLM_QUERY_LESS_EQUAL");
  public final static realm_query_cond_e RLM_QUERY_BETWEEN = new realm_query_cond_e("RLM_QUERY_BETWEEN");
  public final static realm_query_cond_e RLM_QUERY_CONTAINS = new realm_query_cond_e("RLM_QUERY_CONTAINS");
  public final static realm_query_cond_e RLM_QUERY_LIKE = new realm_query_cond_e("RLM_QUERY_LIKE");
  public final static realm_query_cond_e RLM_QUERY_BEGINS_WITH = new realm_query_cond_e("RLM_QUERY_BEGINS_WITH");
  public final static realm_query_cond_e RLM_QUERY_ENDS_WITH = new realm_query_cond_e("RLM_QUERY_ENDS_WITH");
  public final static realm_query_cond_e RLM_QUERY_LINKS_TO = new realm_query_cond_e("RLM_QUERY_LINKS_TO");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static realm_query_cond_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + realm_query_cond_e.class + " with value " + swigValue);
  }

  private realm_query_cond_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private realm_query_cond_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private realm_query_cond_e(String swigName, realm_query_cond_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static realm_query_cond_e[] swigValues = { RLM_QUERY_EQUAL, RLM_QUERY_NOT_EQUAL, RLM_QUERY_GREATER, RLM_QUERY_GREATER_EQUAL, RLM_QUERY_LESS, RLM_QUERY_LESS_EQUAL, RLM_QUERY_BETWEEN, RLM_QUERY_CONTAINS, RLM_QUERY_LIKE, RLM_QUERY_BEGINS_WITH, RLM_QUERY_ENDS_WITH, RLM_QUERY_LINKS_TO };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

