/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class realm_errno_e {
  public final static realm_errno_e RLM_ERR_NONE = new realm_errno_e("RLM_ERR_NONE", realmcJNI.RLM_ERR_NONE_get());
  public final static realm_errno_e RLM_ERR_UNKNOWN = new realm_errno_e("RLM_ERR_UNKNOWN");
  public final static realm_errno_e RLM_ERR_OTHER_EXCEPTION = new realm_errno_e("RLM_ERR_OTHER_EXCEPTION");
  public final static realm_errno_e RLM_ERR_OUT_OF_MEMORY = new realm_errno_e("RLM_ERR_OUT_OF_MEMORY");
  public final static realm_errno_e RLM_ERR_NOT_CLONABLE = new realm_errno_e("RLM_ERR_NOT_CLONABLE");
  public final static realm_errno_e RLM_ERR_INVALID_ARGUMENT = new realm_errno_e("RLM_ERR_INVALID_ARGUMENT");
  public final static realm_errno_e RLM_ERR_LOGIC = new realm_errno_e("RLM_ERR_LOGIC");
  public final static realm_errno_e RLM_ERR_NO_SUCH_TABLE = new realm_errno_e("RLM_ERR_NO_SUCH_TABLE");
  public final static realm_errno_e RLM_ERR_TABLE_NAME_IN_USE = new realm_errno_e("RLM_ERR_TABLE_NAME_IN_USE");
  public final static realm_errno_e RLM_ERR_CROSS_TABLE_LINK_TARGET = new realm_errno_e("RLM_ERR_CROSS_TABLE_LINK_TARGET");
  public final static realm_errno_e RLM_ERR_DESCRIPTOR_MISMATCH = new realm_errno_e("RLM_ERR_DESCRIPTOR_MISMATCH");
  public final static realm_errno_e RLM_ERR_UNSUPPORTED_FILE_FORMAT_VERSION = new realm_errno_e("RLM_ERR_UNSUPPORTED_FILE_FORMAT_VERSION");
  public final static realm_errno_e RLM_ERR_MULTIPLE_SYNC_AGENTS = new realm_errno_e("RLM_ERR_MULTIPLE_SYNC_AGENTS");
  public final static realm_errno_e RLM_ERR_ADDRESS_SPACE_EXHAUSTED = new realm_errno_e("RLM_ERR_ADDRESS_SPACE_EXHAUSTED");
  public final static realm_errno_e RLM_ERR_MAXIMUM_FILE_SIZE_EXCEEDED = new realm_errno_e("RLM_ERR_MAXIMUM_FILE_SIZE_EXCEEDED");
  public final static realm_errno_e RLM_ERR_OUT_OF_DISK_SPACE = new realm_errno_e("RLM_ERR_OUT_OF_DISK_SPACE");
  public final static realm_errno_e RLM_ERR_KEY_NOT_FOUND = new realm_errno_e("RLM_ERR_KEY_NOT_FOUND");
  public final static realm_errno_e RLM_ERR_COLUMN_NOT_FOUND = new realm_errno_e("RLM_ERR_COLUMN_NOT_FOUND");
  public final static realm_errno_e RLM_ERR_COLUMN_ALREADY_EXISTS = new realm_errno_e("RLM_ERR_COLUMN_ALREADY_EXISTS");
  public final static realm_errno_e RLM_ERR_KEY_ALREADY_USED = new realm_errno_e("RLM_ERR_KEY_ALREADY_USED");
  public final static realm_errno_e RLM_ERR_SERIALIZATION_ERROR = new realm_errno_e("RLM_ERR_SERIALIZATION_ERROR");
  public final static realm_errno_e RLM_ERR_INVALID_PATH_ERROR = new realm_errno_e("RLM_ERR_INVALID_PATH_ERROR");
  public final static realm_errno_e RLM_ERR_DUPLICATE_PRIMARY_KEY_VALUE = new realm_errno_e("RLM_ERR_DUPLICATE_PRIMARY_KEY_VALUE");
  public final static realm_errno_e RLM_ERR_INDEX_OUT_OF_BOUNDS = new realm_errno_e("RLM_ERR_INDEX_OUT_OF_BOUNDS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static realm_errno_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + realm_errno_e.class + " with value " + swigValue);
  }

  private realm_errno_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private realm_errno_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private realm_errno_e(String swigName, realm_errno_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static realm_errno_e[] swigValues = { RLM_ERR_NONE, RLM_ERR_UNKNOWN, RLM_ERR_OTHER_EXCEPTION, RLM_ERR_OUT_OF_MEMORY, RLM_ERR_NOT_CLONABLE, RLM_ERR_INVALID_ARGUMENT, RLM_ERR_LOGIC, RLM_ERR_NO_SUCH_TABLE, RLM_ERR_TABLE_NAME_IN_USE, RLM_ERR_CROSS_TABLE_LINK_TARGET, RLM_ERR_DESCRIPTOR_MISMATCH, RLM_ERR_UNSUPPORTED_FILE_FORMAT_VERSION, RLM_ERR_MULTIPLE_SYNC_AGENTS, RLM_ERR_ADDRESS_SPACE_EXHAUSTED, RLM_ERR_MAXIMUM_FILE_SIZE_EXCEEDED, RLM_ERR_OUT_OF_DISK_SPACE, RLM_ERR_KEY_NOT_FOUND, RLM_ERR_COLUMN_NOT_FOUND, RLM_ERR_COLUMN_ALREADY_EXISTS, RLM_ERR_KEY_ALREADY_USED, RLM_ERR_SERIALIZATION_ERROR, RLM_ERR_INVALID_PATH_ERROR, RLM_ERR_DUPLICATE_PRIMARY_KEY_VALUE, RLM_ERR_INDEX_OUT_OF_BOUNDS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

