/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class realm_class_flags_e {
  public final static realm_class_flags_e RLM_CLASS_NORMAL = new realm_class_flags_e("RLM_CLASS_NORMAL", realmcJNI.RLM_CLASS_NORMAL_get());
  public final static realm_class_flags_e RLM_CLASS_EMBEDDED = new realm_class_flags_e("RLM_CLASS_EMBEDDED", realmcJNI.RLM_CLASS_EMBEDDED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static realm_class_flags_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + realm_class_flags_e.class + " with value " + swigValue);
  }

  private realm_class_flags_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private realm_class_flags_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private realm_class_flags_e(String swigName, realm_class_flags_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static realm_class_flags_e[] swigValues = { RLM_CLASS_NORMAL, RLM_CLASS_EMBEDDED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

