/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class realm_schema_mode_e {
  public final static realm_schema_mode_e RLM_SCHEMA_MODE_AUTOMATIC = new realm_schema_mode_e("RLM_SCHEMA_MODE_AUTOMATIC");
  public final static realm_schema_mode_e RLM_SCHEMA_MODE_IMMUTABLE = new realm_schema_mode_e("RLM_SCHEMA_MODE_IMMUTABLE");
  public final static realm_schema_mode_e RLM_SCHEMA_MODE_READ_ONLY_ALTERNATIVE = new realm_schema_mode_e("RLM_SCHEMA_MODE_READ_ONLY_ALTERNATIVE");
  public final static realm_schema_mode_e RLM_SCHEMA_MODE_RESET_FILE = new realm_schema_mode_e("RLM_SCHEMA_MODE_RESET_FILE");
  public final static realm_schema_mode_e RLM_SCHEMA_MODE_ADDITIVE = new realm_schema_mode_e("RLM_SCHEMA_MODE_ADDITIVE");
  public final static realm_schema_mode_e RLM_SCHEMA_MODE_MANUAL = new realm_schema_mode_e("RLM_SCHEMA_MODE_MANUAL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static realm_schema_mode_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + realm_schema_mode_e.class + " with value " + swigValue);
  }

  private realm_schema_mode_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private realm_schema_mode_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private realm_schema_mode_e(String swigName, realm_schema_mode_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static realm_schema_mode_e[] swigValues = { RLM_SCHEMA_MODE_AUTOMATIC, RLM_SCHEMA_MODE_IMMUTABLE, RLM_SCHEMA_MODE_READ_ONLY_ALTERNATIVE, RLM_SCHEMA_MODE_RESET_FILE, RLM_SCHEMA_MODE_ADDITIVE, RLM_SCHEMA_MODE_MANUAL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

