/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class realm_property_flags_e {
  public final static realm_property_flags_e RLM_PROPERTY_NORMAL = new realm_property_flags_e("RLM_PROPERTY_NORMAL", realmcJNI.RLM_PROPERTY_NORMAL_get());
  public final static realm_property_flags_e RLM_PROPERTY_NULLABLE = new realm_property_flags_e("RLM_PROPERTY_NULLABLE", realmcJNI.RLM_PROPERTY_NULLABLE_get());
  public final static realm_property_flags_e RLM_PROPERTY_PRIMARY_KEY = new realm_property_flags_e("RLM_PROPERTY_PRIMARY_KEY", realmcJNI.RLM_PROPERTY_PRIMARY_KEY_get());
  public final static realm_property_flags_e RLM_PROPERTY_INDEXED = new realm_property_flags_e("RLM_PROPERTY_INDEXED", realmcJNI.RLM_PROPERTY_INDEXED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static realm_property_flags_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + realm_property_flags_e.class + " with value " + swigValue);
  }

  private realm_property_flags_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private realm_property_flags_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private realm_property_flags_e(String swigName, realm_property_flags_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static realm_property_flags_e[] swigValues = { RLM_PROPERTY_NORMAL, RLM_PROPERTY_NULLABLE, RLM_PROPERTY_PRIMARY_KEY, RLM_PROPERTY_INDEXED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

