/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class realmc {
  public static void realm_table_key_t_table_key_set(SWIGTYPE_p_realm_table_key self, SWIGTYPE_p_uint32_t value) {
    realmcJNI.realm_table_key_t_table_key_set(SWIGTYPE_p_realm_table_key.getCPtr(self), SWIGTYPE_p_uint32_t.getCPtr(value));
  }

  public static SWIGTYPE_p_uint32_t realm_table_key_t_table_key_get(SWIGTYPE_p_realm_table_key self) {
    return new SWIGTYPE_p_uint32_t(realmcJNI.realm_table_key_t_table_key_get(SWIGTYPE_p_realm_table_key.getCPtr(self)), true);
  }

  public static SWIGTYPE_p_realm_table_key new_realm_table_key_t() {
    long cPtr = realmcJNI.new_realm_table_key_t();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_table_key(cPtr, true);
  }

  public static void delete_realm_table_key_t(SWIGTYPE_p_realm_table_key self) {
    realmcJNI.delete_realm_table_key_t(SWIGTYPE_p_realm_table_key.getCPtr(self));
  }

  public static void realm_col_key_t_col_key_set(SWIGTYPE_p_realm_col_key self, SWIGTYPE_p_int64_t value) {
    realmcJNI.realm_col_key_t_col_key_set(SWIGTYPE_p_realm_col_key.getCPtr(self), SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public static SWIGTYPE_p_int64_t realm_col_key_t_col_key_get(SWIGTYPE_p_realm_col_key self) {
    return new SWIGTYPE_p_int64_t(realmcJNI.realm_col_key_t_col_key_get(SWIGTYPE_p_realm_col_key.getCPtr(self)), true);
  }

  public static SWIGTYPE_p_realm_col_key new_realm_col_key_t() {
    long cPtr = realmcJNI.new_realm_col_key_t();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_col_key(cPtr, true);
  }

  public static void delete_realm_col_key_t(SWIGTYPE_p_realm_col_key self) {
    realmcJNI.delete_realm_col_key_t(SWIGTYPE_p_realm_col_key.getCPtr(self));
  }

  public static void realm_obj_key_t_obj_key_set(SWIGTYPE_p_realm_obj_key self, SWIGTYPE_p_int64_t value) {
    realmcJNI.realm_obj_key_t_obj_key_set(SWIGTYPE_p_realm_obj_key.getCPtr(self), SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public static SWIGTYPE_p_int64_t realm_obj_key_t_obj_key_get(SWIGTYPE_p_realm_obj_key self) {
    return new SWIGTYPE_p_int64_t(realmcJNI.realm_obj_key_t_obj_key_get(SWIGTYPE_p_realm_obj_key.getCPtr(self)), true);
  }

  public static SWIGTYPE_p_realm_obj_key new_realm_obj_key_t() {
    long cPtr = realmcJNI.new_realm_obj_key_t();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_obj_key(cPtr, true);
  }

  public static void delete_realm_obj_key_t(SWIGTYPE_p_realm_obj_key self) {
    realmcJNI.delete_realm_obj_key_t(SWIGTYPE_p_realm_obj_key.getCPtr(self));
  }

  public static void realm_version_t_version_set(SWIGTYPE_p_realm_version self, SWIGTYPE_p_uint64_t value) {
    realmcJNI.realm_version_t_version_set(SWIGTYPE_p_realm_version.getCPtr(self), SWIGTYPE_p_uint64_t.getCPtr(value));
  }

  public static SWIGTYPE_p_uint64_t realm_version_t_version_get(SWIGTYPE_p_realm_version self) {
    return new SWIGTYPE_p_uint64_t(realmcJNI.realm_version_t_version_get(SWIGTYPE_p_realm_version.getCPtr(self)), true);
  }

  public static SWIGTYPE_p_realm_version new_realm_version_t() {
    long cPtr = realmcJNI.new_realm_version_t();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_version(cPtr, true);
  }

  public static void delete_realm_version_t(SWIGTYPE_p_realm_version self) {
    realmcJNI.delete_realm_version_t(SWIGTYPE_p_realm_version.getCPtr(self));
  }

  public static void realm_string_t_data_set(SWIGTYPE_p_realm_string self, String value) {
    realmcJNI.realm_string_t_data_set(SWIGTYPE_p_realm_string.getCPtr(self), value);
  }

  public static String realm_string_t_data_get(SWIGTYPE_p_realm_string self) {
    return realmcJNI.realm_string_t_data_get(SWIGTYPE_p_realm_string.getCPtr(self));
  }

  public static void realm_string_t_size_set(SWIGTYPE_p_realm_string self, long value) {
    realmcJNI.realm_string_t_size_set(SWIGTYPE_p_realm_string.getCPtr(self), value);
  }

  public static long realm_string_t_size_get(SWIGTYPE_p_realm_string self) {
    return realmcJNI.realm_string_t_size_get(SWIGTYPE_p_realm_string.getCPtr(self));
  }

  public static SWIGTYPE_p_realm_string new_realm_string_t() {
    long cPtr = realmcJNI.new_realm_string_t();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_string(cPtr, true);
  }

  public static void delete_realm_string_t(SWIGTYPE_p_realm_string self) {
    realmcJNI.delete_realm_string_t(SWIGTYPE_p_realm_string.getCPtr(self));
  }

  public static void realm_binary_t_data_set(SWIGTYPE_p_realm_binary self, SWIGTYPE_p_uint8_t value) {
    realmcJNI.realm_binary_t_data_set(SWIGTYPE_p_realm_binary.getCPtr(self), SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public static SWIGTYPE_p_uint8_t realm_binary_t_data_get(SWIGTYPE_p_realm_binary self) {
    long cPtr = realmcJNI.realm_binary_t_data_get(SWIGTYPE_p_realm_binary.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public static void realm_binary_t_size_set(SWIGTYPE_p_realm_binary self, long value) {
    realmcJNI.realm_binary_t_size_set(SWIGTYPE_p_realm_binary.getCPtr(self), value);
  }

  public static long realm_binary_t_size_get(SWIGTYPE_p_realm_binary self) {
    return realmcJNI.realm_binary_t_size_get(SWIGTYPE_p_realm_binary.getCPtr(self));
  }

  public static SWIGTYPE_p_realm_binary new_realm_binary_t() {
    long cPtr = realmcJNI.new_realm_binary_t();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_binary(cPtr, true);
  }

  public static void delete_realm_binary_t(SWIGTYPE_p_realm_binary self) {
    realmcJNI.delete_realm_binary_t(SWIGTYPE_p_realm_binary.getCPtr(self));
  }

  public static void realm_timestamp_t_seconds_set(SWIGTYPE_p_realm_timestamp self, SWIGTYPE_p_int64_t value) {
    realmcJNI.realm_timestamp_t_seconds_set(SWIGTYPE_p_realm_timestamp.getCPtr(self), SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public static SWIGTYPE_p_int64_t realm_timestamp_t_seconds_get(SWIGTYPE_p_realm_timestamp self) {
    return new SWIGTYPE_p_int64_t(realmcJNI.realm_timestamp_t_seconds_get(SWIGTYPE_p_realm_timestamp.getCPtr(self)), true);
  }

  public static void realm_timestamp_t_nanoseconds_set(SWIGTYPE_p_realm_timestamp self, SWIGTYPE_p_int32_t value) {
    realmcJNI.realm_timestamp_t_nanoseconds_set(SWIGTYPE_p_realm_timestamp.getCPtr(self), SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public static SWIGTYPE_p_int32_t realm_timestamp_t_nanoseconds_get(SWIGTYPE_p_realm_timestamp self) {
    return new SWIGTYPE_p_int32_t(realmcJNI.realm_timestamp_t_nanoseconds_get(SWIGTYPE_p_realm_timestamp.getCPtr(self)), true);
  }

  public static SWIGTYPE_p_realm_timestamp new_realm_timestamp_t() {
    long cPtr = realmcJNI.new_realm_timestamp_t();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_timestamp(cPtr, true);
  }

  public static void delete_realm_timestamp_t(SWIGTYPE_p_realm_timestamp self) {
    realmcJNI.delete_realm_timestamp_t(SWIGTYPE_p_realm_timestamp.getCPtr(self));
  }

  public static void realm_decimal128_t_w_set(SWIGTYPE_p_realm_decimal128 self, SWIGTYPE_p_uint64_t value) {
    realmcJNI.realm_decimal128_t_w_set(SWIGTYPE_p_realm_decimal128.getCPtr(self), SWIGTYPE_p_uint64_t.getCPtr(value));
  }

  public static SWIGTYPE_p_uint64_t realm_decimal128_t_w_get(SWIGTYPE_p_realm_decimal128 self) {
    long cPtr = realmcJNI.realm_decimal128_t_w_get(SWIGTYPE_p_realm_decimal128.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint64_t(cPtr, false);
  }

  public static SWIGTYPE_p_realm_decimal128 new_realm_decimal128_t() {
    long cPtr = realmcJNI.new_realm_decimal128_t();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_decimal128(cPtr, true);
  }

  public static void delete_realm_decimal128_t(SWIGTYPE_p_realm_decimal128 self) {
    realmcJNI.delete_realm_decimal128_t(SWIGTYPE_p_realm_decimal128.getCPtr(self));
  }

  public static void realm_link_t_target_table_set(SWIGTYPE_p_realm_link self, SWIGTYPE_p_realm_table_key value) {
    realmcJNI.realm_link_t_target_table_set(SWIGTYPE_p_realm_link.getCPtr(self), SWIGTYPE_p_realm_table_key.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_table_key realm_link_t_target_table_get(SWIGTYPE_p_realm_link self) {
    long cPtr = realmcJNI.realm_link_t_target_table_get(SWIGTYPE_p_realm_link.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_table_key(cPtr, false);
  }

  public static void realm_link_t_target_set(SWIGTYPE_p_realm_link self, SWIGTYPE_p_realm_obj_key value) {
    realmcJNI.realm_link_t_target_set(SWIGTYPE_p_realm_link.getCPtr(self), SWIGTYPE_p_realm_obj_key.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_obj_key realm_link_t_target_get(SWIGTYPE_p_realm_link self) {
    long cPtr = realmcJNI.realm_link_t_target_get(SWIGTYPE_p_realm_link.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_obj_key(cPtr, false);
  }

  public static SWIGTYPE_p_realm_link new_realm_link_t() {
    long cPtr = realmcJNI.new_realm_link_t();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_link(cPtr, true);
  }

  public static void delete_realm_link_t(SWIGTYPE_p_realm_link self) {
    realmcJNI.delete_realm_link_t(SWIGTYPE_p_realm_link.getCPtr(self));
  }

  public static void realm_object_id_t_bytes_set(SWIGTYPE_p_realm_object_id self, SWIGTYPE_p_uint8_t value) {
    realmcJNI.realm_object_id_t_bytes_set(SWIGTYPE_p_realm_object_id.getCPtr(self), SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public static SWIGTYPE_p_uint8_t realm_object_id_t_bytes_get(SWIGTYPE_p_realm_object_id self) {
    long cPtr = realmcJNI.realm_object_id_t_bytes_get(SWIGTYPE_p_realm_object_id.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public static SWIGTYPE_p_realm_object_id new_realm_object_id_t() {
    long cPtr = realmcJNI.new_realm_object_id_t();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_object_id(cPtr, true);
  }

  public static void delete_realm_object_id_t(SWIGTYPE_p_realm_object_id self) {
    realmcJNI.delete_realm_object_id_t(SWIGTYPE_p_realm_object_id.getCPtr(self));
  }

  public static void realm_value_t_integer_set(SWIGTYPE_p_realm_value self, SWIGTYPE_p_int64_t value) {
    realmcJNI.realm_value_t_integer_set(SWIGTYPE_p_realm_value.getCPtr(self), SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public static SWIGTYPE_p_int64_t realm_value_t_integer_get(SWIGTYPE_p_realm_value self) {
    return new SWIGTYPE_p_int64_t(realmcJNI.realm_value_t_integer_get(SWIGTYPE_p_realm_value.getCPtr(self)), true);
  }

  public static void realm_value_t__boolean_set(SWIGTYPE_p_realm_value self, boolean value) {
    realmcJNI.realm_value_t__boolean_set(SWIGTYPE_p_realm_value.getCPtr(self), value);
  }

  public static boolean realm_value_t__boolean_get(SWIGTYPE_p_realm_value self) {
    return realmcJNI.realm_value_t__boolean_get(SWIGTYPE_p_realm_value.getCPtr(self));
  }

  public static void realm_value_t_string_set(SWIGTYPE_p_realm_value self, SWIGTYPE_p_realm_string value) {
    realmcJNI.realm_value_t_string_set(SWIGTYPE_p_realm_value.getCPtr(self), SWIGTYPE_p_realm_string.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_string realm_value_t_string_get(SWIGTYPE_p_realm_value self) {
    long cPtr = realmcJNI.realm_value_t_string_get(SWIGTYPE_p_realm_value.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_string(cPtr, false);
  }

  public static void realm_value_t_binary_set(SWIGTYPE_p_realm_value self, SWIGTYPE_p_realm_binary value) {
    realmcJNI.realm_value_t_binary_set(SWIGTYPE_p_realm_value.getCPtr(self), SWIGTYPE_p_realm_binary.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_binary realm_value_t_binary_get(SWIGTYPE_p_realm_value self) {
    long cPtr = realmcJNI.realm_value_t_binary_get(SWIGTYPE_p_realm_value.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_binary(cPtr, false);
  }

  public static void realm_value_t_timestamp_set(SWIGTYPE_p_realm_value self, SWIGTYPE_p_realm_timestamp value) {
    realmcJNI.realm_value_t_timestamp_set(SWIGTYPE_p_realm_value.getCPtr(self), SWIGTYPE_p_realm_timestamp.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_timestamp realm_value_t_timestamp_get(SWIGTYPE_p_realm_value self) {
    long cPtr = realmcJNI.realm_value_t_timestamp_get(SWIGTYPE_p_realm_value.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_timestamp(cPtr, false);
  }

  public static void realm_value_t_fnum_set(SWIGTYPE_p_realm_value self, float value) {
    realmcJNI.realm_value_t_fnum_set(SWIGTYPE_p_realm_value.getCPtr(self), value);
  }

  public static float realm_value_t_fnum_get(SWIGTYPE_p_realm_value self) {
    return realmcJNI.realm_value_t_fnum_get(SWIGTYPE_p_realm_value.getCPtr(self));
  }

  public static void realm_value_t_dnum_set(SWIGTYPE_p_realm_value self, double value) {
    realmcJNI.realm_value_t_dnum_set(SWIGTYPE_p_realm_value.getCPtr(self), value);
  }

  public static double realm_value_t_dnum_get(SWIGTYPE_p_realm_value self) {
    return realmcJNI.realm_value_t_dnum_get(SWIGTYPE_p_realm_value.getCPtr(self));
  }

  public static void realm_value_t_decimal128_set(SWIGTYPE_p_realm_value self, SWIGTYPE_p_realm_decimal128 value) {
    realmcJNI.realm_value_t_decimal128_set(SWIGTYPE_p_realm_value.getCPtr(self), SWIGTYPE_p_realm_decimal128.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_decimal128 realm_value_t_decimal128_get(SWIGTYPE_p_realm_value self) {
    long cPtr = realmcJNI.realm_value_t_decimal128_get(SWIGTYPE_p_realm_value.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_decimal128(cPtr, false);
  }

  public static void realm_value_t_object_id_set(SWIGTYPE_p_realm_value self, SWIGTYPE_p_realm_object_id value) {
    realmcJNI.realm_value_t_object_id_set(SWIGTYPE_p_realm_value.getCPtr(self), SWIGTYPE_p_realm_object_id.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_object_id realm_value_t_object_id_get(SWIGTYPE_p_realm_value self) {
    long cPtr = realmcJNI.realm_value_t_object_id_get(SWIGTYPE_p_realm_value.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_object_id(cPtr, false);
  }

  public static void realm_value_t_link_set(SWIGTYPE_p_realm_value self, SWIGTYPE_p_realm_link value) {
    realmcJNI.realm_value_t_link_set(SWIGTYPE_p_realm_value.getCPtr(self), SWIGTYPE_p_realm_link.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_link realm_value_t_link_get(SWIGTYPE_p_realm_value self) {
    long cPtr = realmcJNI.realm_value_t_link_get(SWIGTYPE_p_realm_value.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_link(cPtr, false);
  }

  public static void realm_value_t_data_set(SWIGTYPE_p_realm_value self, String value) {
    realmcJNI.realm_value_t_data_set(SWIGTYPE_p_realm_value.getCPtr(self), value);
  }

  public static String realm_value_t_data_get(SWIGTYPE_p_realm_value self) {
    return realmcJNI.realm_value_t_data_get(SWIGTYPE_p_realm_value.getCPtr(self));
  }

  public static void realm_value_t_type_set(SWIGTYPE_p_realm_value self, realm_value_type_e value) {
    realmcJNI.realm_value_t_type_set(SWIGTYPE_p_realm_value.getCPtr(self), value.swigValue());
  }

  public static realm_value_type_e realm_value_t_type_get(SWIGTYPE_p_realm_value self) {
    return realm_value_type_e.swigToEnum(realmcJNI.realm_value_t_type_get(SWIGTYPE_p_realm_value.getCPtr(self)));
  }

  public static SWIGTYPE_p_realm_value new_realm_value_t() {
    long cPtr = realmcJNI.new_realm_value_t();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_value(cPtr, true);
  }

  public static void delete_realm_value_t(SWIGTYPE_p_realm_value self) {
    realmcJNI.delete_realm_value_t(SWIGTYPE_p_realm_value.getCPtr(self));
  }

  public static void realm_error_t_error_set(SWIGTYPE_p_realm_error self, realm_errno_e value) {
    realmcJNI.realm_error_t_error_set(SWIGTYPE_p_realm_error.getCPtr(self), value.swigValue());
  }

  public static realm_errno_e realm_error_t_error_get(SWIGTYPE_p_realm_error self) {
    return realm_errno_e.swigToEnum(realmcJNI.realm_error_t_error_get(SWIGTYPE_p_realm_error.getCPtr(self)));
  }

  public static void realm_error_t_message_set(SWIGTYPE_p_realm_error self, SWIGTYPE_p_realm_string value) {
    realmcJNI.realm_error_t_message_set(SWIGTYPE_p_realm_error.getCPtr(self), SWIGTYPE_p_realm_string.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_string realm_error_t_message_get(SWIGTYPE_p_realm_error self) {
    long cPtr = realmcJNI.realm_error_t_message_get(SWIGTYPE_p_realm_error.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_string(cPtr, false);
  }

  public static SWIGTYPE_p_realm_error_kind realm_error_t_kind_get(SWIGTYPE_p_realm_error self) {
    long cPtr = realmcJNI.realm_error_t_kind_get(SWIGTYPE_p_realm_error.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_error_kind(cPtr, false);
  }

  public static SWIGTYPE_p_realm_error new_realm_error_t() {
    long cPtr = realmcJNI.new_realm_error_t();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_error(cPtr, true);
  }

  public static void delete_realm_error_t(SWIGTYPE_p_realm_error self) {
    realmcJNI.delete_realm_error_t(SWIGTYPE_p_realm_error.getCPtr(self));
  }

  public static void realm_error_kind_code_set(SWIGTYPE_p_realm_error_kind self, int value) {
    realmcJNI.realm_error_kind_code_set(SWIGTYPE_p_realm_error_kind.getCPtr(self), value);
  }

  public static int realm_error_kind_code_get(SWIGTYPE_p_realm_error_kind self) {
    return realmcJNI.realm_error_kind_code_get(SWIGTYPE_p_realm_error_kind.getCPtr(self));
  }

  public static void realm_error_kind_logic_error_kind_set(SWIGTYPE_p_realm_error_kind self, realm_logic_error_kind_e value) {
    realmcJNI.realm_error_kind_logic_error_kind_set(SWIGTYPE_p_realm_error_kind.getCPtr(self), value.swigValue());
  }

  public static realm_logic_error_kind_e realm_error_kind_logic_error_kind_get(SWIGTYPE_p_realm_error_kind self) {
    return realm_logic_error_kind_e.swigToEnum(realmcJNI.realm_error_kind_logic_error_kind_get(SWIGTYPE_p_realm_error_kind.getCPtr(self)));
  }

  public static SWIGTYPE_p_realm_error_kind new_realm_error_kind() {
    long cPtr = realmcJNI.new_realm_error_kind();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_error_kind(cPtr, true);
  }

  public static void delete_realm_error_kind(SWIGTYPE_p_realm_error_kind self) {
    realmcJNI.delete_realm_error_kind(SWIGTYPE_p_realm_error_kind.getCPtr(self));
  }

  public static void realm_property_info_t_name_set(SWIGTYPE_p_realm_property_info self, SWIGTYPE_p_realm_string value) {
    realmcJNI.realm_property_info_t_name_set(SWIGTYPE_p_realm_property_info.getCPtr(self), SWIGTYPE_p_realm_string.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_string realm_property_info_t_name_get(SWIGTYPE_p_realm_property_info self) {
    long cPtr = realmcJNI.realm_property_info_t_name_get(SWIGTYPE_p_realm_property_info.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_string(cPtr, false);
  }

  public static void realm_property_info_t_public_name_set(SWIGTYPE_p_realm_property_info self, SWIGTYPE_p_realm_string value) {
    realmcJNI.realm_property_info_t_public_name_set(SWIGTYPE_p_realm_property_info.getCPtr(self), SWIGTYPE_p_realm_string.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_string realm_property_info_t_public_name_get(SWIGTYPE_p_realm_property_info self) {
    long cPtr = realmcJNI.realm_property_info_t_public_name_get(SWIGTYPE_p_realm_property_info.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_string(cPtr, false);
  }

  public static void realm_property_info_t_type_set(SWIGTYPE_p_realm_property_info self, realm_property_type_e value) {
    realmcJNI.realm_property_info_t_type_set(SWIGTYPE_p_realm_property_info.getCPtr(self), value.swigValue());
  }

  public static realm_property_type_e realm_property_info_t_type_get(SWIGTYPE_p_realm_property_info self) {
    return realm_property_type_e.swigToEnum(realmcJNI.realm_property_info_t_type_get(SWIGTYPE_p_realm_property_info.getCPtr(self)));
  }

  public static void realm_property_info_t_collection_type_set(SWIGTYPE_p_realm_property_info self, realm_collection_type_e value) {
    realmcJNI.realm_property_info_t_collection_type_set(SWIGTYPE_p_realm_property_info.getCPtr(self), value.swigValue());
  }

  public static realm_collection_type_e realm_property_info_t_collection_type_get(SWIGTYPE_p_realm_property_info self) {
    return realm_collection_type_e.swigToEnum(realmcJNI.realm_property_info_t_collection_type_get(SWIGTYPE_p_realm_property_info.getCPtr(self)));
  }

  public static void realm_property_info_t_link_target_set(SWIGTYPE_p_realm_property_info self, SWIGTYPE_p_realm_string value) {
    realmcJNI.realm_property_info_t_link_target_set(SWIGTYPE_p_realm_property_info.getCPtr(self), SWIGTYPE_p_realm_string.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_string realm_property_info_t_link_target_get(SWIGTYPE_p_realm_property_info self) {
    long cPtr = realmcJNI.realm_property_info_t_link_target_get(SWIGTYPE_p_realm_property_info.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_string(cPtr, false);
  }

  public static void realm_property_info_t_link_origin_property_name_set(SWIGTYPE_p_realm_property_info self, SWIGTYPE_p_realm_string value) {
    realmcJNI.realm_property_info_t_link_origin_property_name_set(SWIGTYPE_p_realm_property_info.getCPtr(self), SWIGTYPE_p_realm_string.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_string realm_property_info_t_link_origin_property_name_get(SWIGTYPE_p_realm_property_info self) {
    long cPtr = realmcJNI.realm_property_info_t_link_origin_property_name_get(SWIGTYPE_p_realm_property_info.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_string(cPtr, false);
  }

  public static void realm_property_info_t_key_set(SWIGTYPE_p_realm_property_info self, SWIGTYPE_p_realm_col_key value) {
    realmcJNI.realm_property_info_t_key_set(SWIGTYPE_p_realm_property_info.getCPtr(self), SWIGTYPE_p_realm_col_key.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_col_key realm_property_info_t_key_get(SWIGTYPE_p_realm_property_info self) {
    long cPtr = realmcJNI.realm_property_info_t_key_get(SWIGTYPE_p_realm_property_info.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_col_key(cPtr, false);
  }

  public static void realm_property_info_t_flags_set(SWIGTYPE_p_realm_property_info self, int value) {
    realmcJNI.realm_property_info_t_flags_set(SWIGTYPE_p_realm_property_info.getCPtr(self), value);
  }

  public static int realm_property_info_t_flags_get(SWIGTYPE_p_realm_property_info self) {
    return realmcJNI.realm_property_info_t_flags_get(SWIGTYPE_p_realm_property_info.getCPtr(self));
  }

  public static SWIGTYPE_p_realm_property_info new_realm_property_info_t() {
    long cPtr = realmcJNI.new_realm_property_info_t();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_property_info(cPtr, true);
  }

  public static void delete_realm_property_info_t(SWIGTYPE_p_realm_property_info self) {
    realmcJNI.delete_realm_property_info_t(SWIGTYPE_p_realm_property_info.getCPtr(self));
  }

  public static void realm_class_info_t_name_set(SWIGTYPE_p_realm_class_info self, SWIGTYPE_p_realm_string value) {
    realmcJNI.realm_class_info_t_name_set(SWIGTYPE_p_realm_class_info.getCPtr(self), SWIGTYPE_p_realm_string.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_string realm_class_info_t_name_get(SWIGTYPE_p_realm_class_info self) {
    long cPtr = realmcJNI.realm_class_info_t_name_get(SWIGTYPE_p_realm_class_info.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_string(cPtr, false);
  }

  public static void realm_class_info_t_primary_key_set(SWIGTYPE_p_realm_class_info self, SWIGTYPE_p_realm_string value) {
    realmcJNI.realm_class_info_t_primary_key_set(SWIGTYPE_p_realm_class_info.getCPtr(self), SWIGTYPE_p_realm_string.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_string realm_class_info_t_primary_key_get(SWIGTYPE_p_realm_class_info self) {
    long cPtr = realmcJNI.realm_class_info_t_primary_key_get(SWIGTYPE_p_realm_class_info.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_string(cPtr, false);
  }

  public static void realm_class_info_t_num_properties_set(SWIGTYPE_p_realm_class_info self, long value) {
    realmcJNI.realm_class_info_t_num_properties_set(SWIGTYPE_p_realm_class_info.getCPtr(self), value);
  }

  public static long realm_class_info_t_num_properties_get(SWIGTYPE_p_realm_class_info self) {
    return realmcJNI.realm_class_info_t_num_properties_get(SWIGTYPE_p_realm_class_info.getCPtr(self));
  }

  public static void realm_class_info_t_num_computed_properties_set(SWIGTYPE_p_realm_class_info self, long value) {
    realmcJNI.realm_class_info_t_num_computed_properties_set(SWIGTYPE_p_realm_class_info.getCPtr(self), value);
  }

  public static long realm_class_info_t_num_computed_properties_get(SWIGTYPE_p_realm_class_info self) {
    return realmcJNI.realm_class_info_t_num_computed_properties_get(SWIGTYPE_p_realm_class_info.getCPtr(self));
  }

  public static void realm_class_info_t_key_set(SWIGTYPE_p_realm_class_info self, SWIGTYPE_p_realm_table_key value) {
    realmcJNI.realm_class_info_t_key_set(SWIGTYPE_p_realm_class_info.getCPtr(self), SWIGTYPE_p_realm_table_key.getCPtr(value));
  }

  public static SWIGTYPE_p_realm_table_key realm_class_info_t_key_get(SWIGTYPE_p_realm_class_info self) {
    long cPtr = realmcJNI.realm_class_info_t_key_get(SWIGTYPE_p_realm_class_info.getCPtr(self));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_table_key(cPtr, false);
  }

  public static void realm_class_info_t_flags_set(SWIGTYPE_p_realm_class_info self, int value) {
    realmcJNI.realm_class_info_t_flags_set(SWIGTYPE_p_realm_class_info.getCPtr(self), value);
  }

  public static int realm_class_info_t_flags_get(SWIGTYPE_p_realm_class_info self) {
    return realmcJNI.realm_class_info_t_flags_get(SWIGTYPE_p_realm_class_info.getCPtr(self));
  }

  public static SWIGTYPE_p_realm_class_info new_realm_class_info_t() {
    long cPtr = realmcJNI.new_realm_class_info_t();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_class_info(cPtr, true);
  }

  public static void delete_realm_class_info_t(SWIGTYPE_p_realm_class_info self) {
    realmcJNI.delete_realm_class_info_t(SWIGTYPE_p_realm_class_info.getCPtr(self));
  }

  public static String realm_get_library_version() {
    return realmcJNI.realm_get_library_version();
  }

  public static void realm_get_library_version_numbers(SWIGTYPE_p_int out_major, SWIGTYPE_p_int out_minor, SWIGTYPE_p_int out_patch, SWIGTYPE_p_p_char out_extra) {
    realmcJNI.realm_get_library_version_numbers(SWIGTYPE_p_int.getCPtr(out_major), SWIGTYPE_p_int.getCPtr(out_minor), SWIGTYPE_p_int.getCPtr(out_patch), SWIGTYPE_p_p_char.getCPtr(out_extra));
  }

  public static boolean realm_get_last_error(SWIGTYPE_p_realm_error err) {
    return realmcJNI.realm_get_last_error(SWIGTYPE_p_realm_error.getCPtr(err));
  }

  public static boolean realm_clear_last_error() {
    return realmcJNI.realm_clear_last_error();
  }

  public static void realm_release(SWIGTYPE_p_void ptr) {
    realmcJNI.realm_release(SWIGTYPE_p_void.getCPtr(ptr));
  }

  public static SWIGTYPE_p_void realm_clone(SWIGTYPE_p_void arg0) {
    long cPtr = realmcJNI.realm_clone(SWIGTYPE_p_void.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static boolean realm_is_frozen(SWIGTYPE_p_void arg0) {
    return realmcJNI.realm_is_frozen(SWIGTYPE_p_void.getCPtr(arg0));
  }

  public static SWIGTYPE_p_realm_config realm_config_new() {
    long cPtr = realmcJNI.realm_config_new();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_config(cPtr, false);
  }

  public static boolean realm_config_set_path(SWIGTYPE_p_realm_config arg0, SWIGTYPE_p_realm_string arg1) {
    return realmcJNI.realm_config_set_path(SWIGTYPE_p_realm_config.getCPtr(arg0), SWIGTYPE_p_realm_string.getCPtr(arg1));
  }

  public static boolean realm_config_set_encryption_key(SWIGTYPE_p_realm_config arg0, SWIGTYPE_p_realm_binary arg1) {
    return realmcJNI.realm_config_set_encryption_key(SWIGTYPE_p_realm_config.getCPtr(arg0), SWIGTYPE_p_realm_binary.getCPtr(arg1));
  }

  public static boolean realm_config_set_schema(SWIGTYPE_p_realm_config arg0, SWIGTYPE_p_realm_schema arg1) {
    return realmcJNI.realm_config_set_schema(SWIGTYPE_p_realm_config.getCPtr(arg0), SWIGTYPE_p_realm_schema.getCPtr(arg1));
  }

  public static boolean realm_config_set_schema_version(SWIGTYPE_p_realm_config arg0, SWIGTYPE_p_uint64_t version) {
    return realmcJNI.realm_config_set_schema_version(SWIGTYPE_p_realm_config.getCPtr(arg0), SWIGTYPE_p_uint64_t.getCPtr(version));
  }

  public static boolean realm_config_set_schema_mode(SWIGTYPE_p_realm_config arg0, realm_schema_mode_e arg1) {
    return realmcJNI.realm_config_set_schema_mode(SWIGTYPE_p_realm_config.getCPtr(arg0), arg1.swigValue());
  }

  public static boolean realm_config_set_migration_function(SWIGTYPE_p_realm_config arg0, SWIGTYPE_p_f_p_void_p_struct_shared_realm_p_struct_shared_realm_p_q_const__struct_realm_schema__void arg1, SWIGTYPE_p_void userdata) {
    return realmcJNI.realm_config_set_migration_function(SWIGTYPE_p_realm_config.getCPtr(arg0), SWIGTYPE_p_f_p_void_p_struct_shared_realm_p_struct_shared_realm_p_q_const__struct_realm_schema__void.getCPtr(arg1), SWIGTYPE_p_void.getCPtr(userdata));
  }

  public static boolean realm_config_set_data_initialization_function(SWIGTYPE_p_realm_config arg0, SWIGTYPE_p_f_p_void_p_struct_shared_realm__void arg1, SWIGTYPE_p_void userdata) {
    return realmcJNI.realm_config_set_data_initialization_function(SWIGTYPE_p_realm_config.getCPtr(arg0), SWIGTYPE_p_f_p_void_p_struct_shared_realm__void.getCPtr(arg1), SWIGTYPE_p_void.getCPtr(userdata));
  }

  public static boolean realm_config_set_should_compact_on_launch_function(SWIGTYPE_p_realm_config arg0, SWIGTYPE_p_f_p_void_uint64_t_uint64_t__bool arg1, SWIGTYPE_p_void userdata) {
    return realmcJNI.realm_config_set_should_compact_on_launch_function(SWIGTYPE_p_realm_config.getCPtr(arg0), SWIGTYPE_p_f_p_void_uint64_t_uint64_t__bool.getCPtr(arg1), SWIGTYPE_p_void.getCPtr(userdata));
  }

  public static boolean realm_config_set_disable_format_upgrade(SWIGTYPE_p_realm_config arg0, boolean arg1) {
    return realmcJNI.realm_config_set_disable_format_upgrade(SWIGTYPE_p_realm_config.getCPtr(arg0), arg1);
  }

  public static boolean realm_config_set_automatic_change_notifications(SWIGTYPE_p_realm_config arg0, boolean arg1) {
    return realmcJNI.realm_config_set_automatic_change_notifications(SWIGTYPE_p_realm_config.getCPtr(arg0), arg1);
  }

  public static boolean realm_config_set_scheduler(SWIGTYPE_p_realm_config arg0, SWIGTYPE_p_void arg1) {
    return realmcJNI.realm_config_set_scheduler(SWIGTYPE_p_realm_config.getCPtr(arg0), SWIGTYPE_p_void.getCPtr(arg1));
  }

  public static boolean realm_config_set_sync_config(SWIGTYPE_p_realm_config arg0, SWIGTYPE_p_realm_sync_config arg1) {
    return realmcJNI.realm_config_set_sync_config(SWIGTYPE_p_realm_config.getCPtr(arg0), SWIGTYPE_p_realm_sync_config.getCPtr(arg1));
  }

  public static boolean realm_config_set_force_sync_history(SWIGTYPE_p_realm_config arg0, boolean arg1) {
    return realmcJNI.realm_config_set_force_sync_history(SWIGTYPE_p_realm_config.getCPtr(arg0), arg1);
  }

  public static boolean realm_config_set_audit_factory(SWIGTYPE_p_realm_config arg0, SWIGTYPE_p_void arg1) {
    return realmcJNI.realm_config_set_audit_factory(SWIGTYPE_p_realm_config.getCPtr(arg0), SWIGTYPE_p_void.getCPtr(arg1));
  }

  public static boolean realm_config_set_max_number_of_active_versions(SWIGTYPE_p_realm_config arg0, long arg1) {
    return realmcJNI.realm_config_set_max_number_of_active_versions(SWIGTYPE_p_realm_config.getCPtr(arg0), arg1);
  }

  public static SWIGTYPE_p_shared_realm realm_open(SWIGTYPE_p_realm_config config) {
    long cPtr = realmcJNI.realm_open(SWIGTYPE_p_realm_config.getCPtr(config));
    return (cPtr == 0) ? null : new SWIGTYPE_p_shared_realm(cPtr, false);
  }

  public static SWIGTYPE_p_shared_realm _realm_from_native_ptr(SWIGTYPE_p_void pshared_ptr, long n) {
    long cPtr = realmcJNI._realm_from_native_ptr(SWIGTYPE_p_void.getCPtr(pshared_ptr), n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_shared_realm(cPtr, false);
  }

  public static boolean realm_close(SWIGTYPE_p_shared_realm arg0) {
    return realmcJNI.realm_close(SWIGTYPE_p_shared_realm.getCPtr(arg0));
  }

  public static boolean realm_is_closed(SWIGTYPE_p_shared_realm arg0) {
    return realmcJNI.realm_is_closed(SWIGTYPE_p_shared_realm.getCPtr(arg0));
  }

  public static boolean realm_begin_write(SWIGTYPE_p_shared_realm arg0) {
    return realmcJNI.realm_begin_write(SWIGTYPE_p_shared_realm.getCPtr(arg0));
  }

  public static boolean realm_is_writable(SWIGTYPE_p_shared_realm arg0) {
    return realmcJNI.realm_is_writable(SWIGTYPE_p_shared_realm.getCPtr(arg0));
  }

  public static boolean realm_commit(SWIGTYPE_p_shared_realm arg0) {
    return realmcJNI.realm_commit(SWIGTYPE_p_shared_realm.getCPtr(arg0));
  }

  public static boolean realm_rollback(SWIGTYPE_p_shared_realm arg0) {
    return realmcJNI.realm_rollback(SWIGTYPE_p_shared_realm.getCPtr(arg0));
  }

  public static boolean realm_refresh(SWIGTYPE_p_shared_realm arg0) {
    return realmcJNI.realm_refresh(SWIGTYPE_p_shared_realm.getCPtr(arg0));
  }

  public static SWIGTYPE_p_shared_realm realm_freeze(SWIGTYPE_p_shared_realm arg0) {
    long cPtr = realmcJNI.realm_freeze(SWIGTYPE_p_shared_realm.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_shared_realm(cPtr, false);
  }

  public static boolean realm_compact(SWIGTYPE_p_shared_realm arg0, SWIGTYPE_p_bool did_compact) {
    return realmcJNI.realm_compact(SWIGTYPE_p_shared_realm.getCPtr(arg0), SWIGTYPE_p_bool.getCPtr(did_compact));
  }

  public static SWIGTYPE_p_realm_schema realm_schema_new(SWIGTYPE_p_realm_class_info classes, long num_classes, SWIGTYPE_p_p_realm_property_info class_properties) {
    long cPtr = realmcJNI.realm_schema_new(SWIGTYPE_p_realm_class_info.getCPtr(classes), num_classes, SWIGTYPE_p_p_realm_property_info.getCPtr(class_properties));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_schema(cPtr, false);
  }

  public static SWIGTYPE_p_realm_schema realm_get_schema(SWIGTYPE_p_shared_realm arg0) {
    long cPtr = realmcJNI.realm_get_schema(SWIGTYPE_p_shared_realm.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_schema(cPtr, false);
  }

  public static SWIGTYPE_p_void _realm_get_schema_native(SWIGTYPE_p_shared_realm arg0) {
    long cPtr = realmcJNI._realm_get_schema_native(SWIGTYPE_p_shared_realm.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static boolean realm_schema_validate(SWIGTYPE_p_realm_schema arg0) {
    return realmcJNI.realm_schema_validate(SWIGTYPE_p_realm_schema.getCPtr(arg0));
  }

  public static long realm_get_num_classes(SWIGTYPE_p_shared_realm arg0) {
    return realmcJNI.realm_get_num_classes(SWIGTYPE_p_shared_realm.getCPtr(arg0));
  }

  public static boolean realm_get_class_keys(SWIGTYPE_p_shared_realm arg0, SWIGTYPE_p_realm_table_key out_keys, long max, SWIGTYPE_p_size_t out_n) {
    return realmcJNI.realm_get_class_keys(SWIGTYPE_p_shared_realm.getCPtr(arg0), SWIGTYPE_p_realm_table_key.getCPtr(out_keys), max, SWIGTYPE_p_size_t.getCPtr(out_n));
  }

  public static boolean realm_find_class(SWIGTYPE_p_shared_realm arg0, SWIGTYPE_p_realm_string name, SWIGTYPE_p_bool out_found, SWIGTYPE_p_realm_class_info out_class_info) {
    return realmcJNI.realm_find_class(SWIGTYPE_p_shared_realm.getCPtr(arg0), SWIGTYPE_p_realm_string.getCPtr(name), SWIGTYPE_p_bool.getCPtr(out_found), SWIGTYPE_p_realm_class_info.getCPtr(out_class_info));
  }

  public static boolean realm_get_class(SWIGTYPE_p_shared_realm arg0, SWIGTYPE_p_realm_table_key key, SWIGTYPE_p_realm_class_info out_class_info) {
    return realmcJNI.realm_get_class(SWIGTYPE_p_shared_realm.getCPtr(arg0), SWIGTYPE_p_realm_table_key.getCPtr(key), SWIGTYPE_p_realm_class_info.getCPtr(out_class_info));
  }

  public static boolean realm_get_class_properties(SWIGTYPE_p_shared_realm arg0, SWIGTYPE_p_realm_table_key key, SWIGTYPE_p_realm_property_info out_properties, long max, SWIGTYPE_p_size_t out_n) {
    return realmcJNI.realm_get_class_properties(SWIGTYPE_p_shared_realm.getCPtr(arg0), SWIGTYPE_p_realm_table_key.getCPtr(key), SWIGTYPE_p_realm_property_info.getCPtr(out_properties), max, SWIGTYPE_p_size_t.getCPtr(out_n));
  }

  public static boolean realm_get_property_keys(SWIGTYPE_p_shared_realm arg0, SWIGTYPE_p_realm_table_key key, SWIGTYPE_p_realm_col_key out_col_keys, long max, SWIGTYPE_p_size_t out_n) {
    return realmcJNI.realm_get_property_keys(SWIGTYPE_p_shared_realm.getCPtr(arg0), SWIGTYPE_p_realm_table_key.getCPtr(key), SWIGTYPE_p_realm_col_key.getCPtr(out_col_keys), max, SWIGTYPE_p_size_t.getCPtr(out_n));
  }

  public static boolean realm_get_property(SWIGTYPE_p_shared_realm arg0, SWIGTYPE_p_realm_table_key class_key, SWIGTYPE_p_realm_col_key key, SWIGTYPE_p_realm_property_info out_property_info) {
    return realmcJNI.realm_get_property(SWIGTYPE_p_shared_realm.getCPtr(arg0), SWIGTYPE_p_realm_table_key.getCPtr(class_key), SWIGTYPE_p_realm_col_key.getCPtr(key), SWIGTYPE_p_realm_property_info.getCPtr(out_property_info));
  }

  public static boolean realm_find_property(SWIGTYPE_p_shared_realm arg0, SWIGTYPE_p_realm_table_key class_key, SWIGTYPE_p_realm_string name, SWIGTYPE_p_bool out_found, SWIGTYPE_p_realm_property_info out_property_info) {
    return realmcJNI.realm_find_property(SWIGTYPE_p_shared_realm.getCPtr(arg0), SWIGTYPE_p_realm_table_key.getCPtr(class_key), SWIGTYPE_p_realm_string.getCPtr(name), SWIGTYPE_p_bool.getCPtr(out_found), SWIGTYPE_p_realm_property_info.getCPtr(out_property_info));
  }

  public static boolean realm_find_property_by_public_name(SWIGTYPE_p_shared_realm arg0, SWIGTYPE_p_realm_table_key class_key, SWIGTYPE_p_realm_string public_name, SWIGTYPE_p_bool out_found, SWIGTYPE_p_realm_property_info out_property_info) {
    return realmcJNI.realm_find_property_by_public_name(SWIGTYPE_p_shared_realm.getCPtr(arg0), SWIGTYPE_p_realm_table_key.getCPtr(class_key), SWIGTYPE_p_realm_string.getCPtr(public_name), SWIGTYPE_p_bool.getCPtr(out_found), SWIGTYPE_p_realm_property_info.getCPtr(out_property_info));
  }

  public static boolean realm_get_num_objects(SWIGTYPE_p_shared_realm arg0, SWIGTYPE_p_realm_table_key arg1, SWIGTYPE_p_size_t out_count) {
    return realmcJNI.realm_get_num_objects(SWIGTYPE_p_shared_realm.getCPtr(arg0), SWIGTYPE_p_realm_table_key.getCPtr(arg1), SWIGTYPE_p_size_t.getCPtr(out_count));
  }

  public static SWIGTYPE_p_realm_object realm_get_object(SWIGTYPE_p_shared_realm arg0, SWIGTYPE_p_realm_table_key class_key, SWIGTYPE_p_realm_obj_key obj_key) {
    long cPtr = realmcJNI.realm_get_object(SWIGTYPE_p_shared_realm.getCPtr(arg0), SWIGTYPE_p_realm_table_key.getCPtr(class_key), SWIGTYPE_p_realm_obj_key.getCPtr(obj_key));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_object(cPtr, false);
  }

  public static SWIGTYPE_p_realm_object realm_find_object_with_primary_key(SWIGTYPE_p_shared_realm arg0, SWIGTYPE_p_realm_table_key arg1, SWIGTYPE_p_realm_value pk, SWIGTYPE_p_bool out_found) {
    long cPtr = realmcJNI.realm_find_object_with_primary_key(SWIGTYPE_p_shared_realm.getCPtr(arg0), SWIGTYPE_p_realm_table_key.getCPtr(arg1), SWIGTYPE_p_realm_value.getCPtr(pk), SWIGTYPE_p_bool.getCPtr(out_found));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_object(cPtr, false);
  }

  public static SWIGTYPE_p_realm_object realm_create_object(SWIGTYPE_p_shared_realm arg0, SWIGTYPE_p_realm_table_key arg1) {
    long cPtr = realmcJNI.realm_create_object(SWIGTYPE_p_shared_realm.getCPtr(arg0), SWIGTYPE_p_realm_table_key.getCPtr(arg1));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_object(cPtr, false);
  }

  public static SWIGTYPE_p_realm_object realm_create_object_with_primary_key(SWIGTYPE_p_shared_realm arg0, SWIGTYPE_p_realm_table_key arg1, SWIGTYPE_p_realm_value pk) {
    long cPtr = realmcJNI.realm_create_object_with_primary_key(SWIGTYPE_p_shared_realm.getCPtr(arg0), SWIGTYPE_p_realm_table_key.getCPtr(arg1), SWIGTYPE_p_realm_value.getCPtr(pk));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_object(cPtr, false);
  }

  public static SWIGTYPE_p_realm_object _realm_object_from_native_copy(SWIGTYPE_p_void pobj, long n) {
    long cPtr = realmcJNI._realm_object_from_native_copy(SWIGTYPE_p_void.getCPtr(pobj), n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_object(cPtr, false);
  }

  public static SWIGTYPE_p_realm_object _realm_object_from_native_move(SWIGTYPE_p_void pobj, long n) {
    long cPtr = realmcJNI._realm_object_from_native_move(SWIGTYPE_p_void.getCPtr(pobj), n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_object(cPtr, false);
  }

  public static SWIGTYPE_p_void _realm_object_get_native_ptr(SWIGTYPE_p_realm_object arg0) {
    long cPtr = realmcJNI._realm_object_get_native_ptr(SWIGTYPE_p_realm_object.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static boolean realm_object_is_valid(SWIGTYPE_p_realm_object arg0) {
    return realmcJNI.realm_object_is_valid(SWIGTYPE_p_realm_object.getCPtr(arg0));
  }

  public static SWIGTYPE_p_realm_obj_key realm_object_get_key(SWIGTYPE_p_realm_object object) {
    return new SWIGTYPE_p_realm_obj_key(realmcJNI.realm_object_get_key(SWIGTYPE_p_realm_object.getCPtr(object)), true);
  }

  public static SWIGTYPE_p_realm_table_key realm_object_get_table(SWIGTYPE_p_realm_object object) {
    return new SWIGTYPE_p_realm_table_key(realmcJNI.realm_object_get_table(SWIGTYPE_p_realm_object.getCPtr(object)), true);
  }

  public static SWIGTYPE_p_realm_link realm_object_as_link(SWIGTYPE_p_realm_object object) {
    return new SWIGTYPE_p_realm_link(realmcJNI.realm_object_as_link(SWIGTYPE_p_realm_object.getCPtr(object)), true);
  }

  public static boolean realm_get_value(SWIGTYPE_p_realm_object arg0, SWIGTYPE_p_realm_col_key arg1, SWIGTYPE_p_realm_value out_value) {
    return realmcJNI.realm_get_value(SWIGTYPE_p_realm_object.getCPtr(arg0), SWIGTYPE_p_realm_col_key.getCPtr(arg1), SWIGTYPE_p_realm_value.getCPtr(out_value));
  }

  public static boolean realm_set_value(SWIGTYPE_p_realm_object arg0, SWIGTYPE_p_realm_col_key arg1, SWIGTYPE_p_realm_value new_value, boolean is_default) {
    return realmcJNI.realm_set_value(SWIGTYPE_p_realm_object.getCPtr(arg0), SWIGTYPE_p_realm_col_key.getCPtr(arg1), SWIGTYPE_p_realm_value.getCPtr(new_value), is_default);
  }

  public static SWIGTYPE_p_realm_list realm_get_list(SWIGTYPE_p_realm_object arg0, SWIGTYPE_p_realm_col_key arg1) {
    long cPtr = realmcJNI.realm_get_list(SWIGTYPE_p_realm_object.getCPtr(arg0), SWIGTYPE_p_realm_col_key.getCPtr(arg1));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_list(cPtr, false);
  }

  public static SWIGTYPE_p_realm_list _realm_list_from_native_copy(SWIGTYPE_p_void plist, long n) {
    long cPtr = realmcJNI._realm_list_from_native_copy(SWIGTYPE_p_void.getCPtr(plist), n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_list(cPtr, false);
  }

  public static SWIGTYPE_p_realm_list _realm_list_from_native_move(SWIGTYPE_p_void plist, long n) {
    long cPtr = realmcJNI._realm_list_from_native_move(SWIGTYPE_p_void.getCPtr(plist), n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_list(cPtr, false);
  }

  public static long realm_list_size(SWIGTYPE_p_realm_list arg0) {
    return realmcJNI.realm_list_size(SWIGTYPE_p_realm_list.getCPtr(arg0));
  }

  public static boolean realm_list_get_property(SWIGTYPE_p_realm_list arg0, SWIGTYPE_p_realm_property_info out_property_info) {
    return realmcJNI.realm_list_get_property(SWIGTYPE_p_realm_list.getCPtr(arg0), SWIGTYPE_p_realm_property_info.getCPtr(out_property_info));
  }

  public static boolean realm_list_get(SWIGTYPE_p_realm_list arg0, long index, SWIGTYPE_p_realm_value out_value) {
    return realmcJNI.realm_list_get(SWIGTYPE_p_realm_list.getCPtr(arg0), index, SWIGTYPE_p_realm_value.getCPtr(out_value));
  }

  public static boolean realm_list_set(SWIGTYPE_p_realm_list arg0, long index, SWIGTYPE_p_realm_value value) {
    return realmcJNI.realm_list_set(SWIGTYPE_p_realm_list.getCPtr(arg0), index, SWIGTYPE_p_realm_value.getCPtr(value));
  }

  public static boolean realm_list_insert(SWIGTYPE_p_realm_list arg0, long index, SWIGTYPE_p_realm_value value) {
    return realmcJNI.realm_list_insert(SWIGTYPE_p_realm_list.getCPtr(arg0), index, SWIGTYPE_p_realm_value.getCPtr(value));
  }

  public static boolean realm_list_erase(SWIGTYPE_p_realm_list arg0, long index) {
    return realmcJNI.realm_list_erase(SWIGTYPE_p_realm_list.getCPtr(arg0), index);
  }

  public static boolean realm_list_clear(SWIGTYPE_p_realm_list arg0) {
    return realmcJNI.realm_list_clear(SWIGTYPE_p_realm_list.getCPtr(arg0));
  }

  public static boolean realm_list_assign(SWIGTYPE_p_realm_list arg0, SWIGTYPE_p_realm_value values, long num_values) {
    return realmcJNI.realm_list_assign(SWIGTYPE_p_realm_list.getCPtr(arg0), SWIGTYPE_p_realm_value.getCPtr(values), num_values);
  }

  public static SWIGTYPE_p_realm_set _realm_set_from_native_copy(SWIGTYPE_p_void pset, long n) {
    long cPtr = realmcJNI._realm_set_from_native_copy(SWIGTYPE_p_void.getCPtr(pset), n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_set(cPtr, false);
  }

  public static SWIGTYPE_p_realm_set _realm_set_from_native_move(SWIGTYPE_p_void pset, long n) {
    long cPtr = realmcJNI._realm_set_from_native_move(SWIGTYPE_p_void.getCPtr(pset), n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_set(cPtr, false);
  }

  public static SWIGTYPE_p_realm_set realm_get_set(SWIGTYPE_p_realm_object arg0, SWIGTYPE_p_realm_col_key arg1) {
    long cPtr = realmcJNI.realm_get_set(SWIGTYPE_p_realm_object.getCPtr(arg0), SWIGTYPE_p_realm_col_key.getCPtr(arg1));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_set(cPtr, false);
  }

  public static long realm_set_size(SWIGTYPE_p_realm_set arg0) {
    return realmcJNI.realm_set_size(SWIGTYPE_p_realm_set.getCPtr(arg0));
  }

  public static boolean realm_set_get(SWIGTYPE_p_realm_set arg0, long index, SWIGTYPE_p_realm_value out_value) {
    return realmcJNI.realm_set_get(SWIGTYPE_p_realm_set.getCPtr(arg0), index, SWIGTYPE_p_realm_value.getCPtr(out_value));
  }

  public static boolean realm_set_find(SWIGTYPE_p_realm_set arg0, SWIGTYPE_p_realm_value value, SWIGTYPE_p_size_t out_index) {
    return realmcJNI.realm_set_find(SWIGTYPE_p_realm_set.getCPtr(arg0), SWIGTYPE_p_realm_value.getCPtr(value), SWIGTYPE_p_size_t.getCPtr(out_index));
  }

  public static boolean realm_set_insert(SWIGTYPE_p_realm_set arg0, SWIGTYPE_p_realm_value value, long out_index) {
    return realmcJNI.realm_set_insert(SWIGTYPE_p_realm_set.getCPtr(arg0), SWIGTYPE_p_realm_value.getCPtr(value), out_index);
  }

  public static boolean realm_set_erase(SWIGTYPE_p_realm_set arg0, SWIGTYPE_p_realm_value value, SWIGTYPE_p_bool out_erased) {
    return realmcJNI.realm_set_erase(SWIGTYPE_p_realm_set.getCPtr(arg0), SWIGTYPE_p_realm_value.getCPtr(value), SWIGTYPE_p_bool.getCPtr(out_erased));
  }

  public static boolean realm_set_clear(SWIGTYPE_p_realm_set arg0) {
    return realmcJNI.realm_set_clear(SWIGTYPE_p_realm_set.getCPtr(arg0));
  }

  public static boolean realm_set_assign(SWIGTYPE_p_realm_set arg0, SWIGTYPE_p_realm_value values, long num_values) {
    return realmcJNI.realm_set_assign(SWIGTYPE_p_realm_set.getCPtr(arg0), SWIGTYPE_p_realm_value.getCPtr(values), num_values);
  }

  public static SWIGTYPE_p_realm_dictionary _realm_dictionary_from_native_copy(SWIGTYPE_p_void pdict, long n) {
    long cPtr = realmcJNI._realm_dictionary_from_native_copy(SWIGTYPE_p_void.getCPtr(pdict), n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_dictionary(cPtr, false);
  }

  public static SWIGTYPE_p_realm_dictionary _realm_dictionary_from_native_move(SWIGTYPE_p_void pdict, long n) {
    long cPtr = realmcJNI._realm_dictionary_from_native_move(SWIGTYPE_p_void.getCPtr(pdict), n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_dictionary(cPtr, false);
  }

  public static SWIGTYPE_p_realm_dictionary realm_get_dictionary(SWIGTYPE_p_realm_object arg0, SWIGTYPE_p_realm_col_key arg1) {
    long cPtr = realmcJNI.realm_get_dictionary(SWIGTYPE_p_realm_object.getCPtr(arg0), SWIGTYPE_p_realm_col_key.getCPtr(arg1));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_dictionary(cPtr, false);
  }

  public static long realm_dictionary_size(SWIGTYPE_p_realm_dictionary arg0) {
    return realmcJNI.realm_dictionary_size(SWIGTYPE_p_realm_dictionary.getCPtr(arg0));
  }

  public static boolean realm_dictionary_get(SWIGTYPE_p_realm_dictionary arg0, SWIGTYPE_p_realm_value key, SWIGTYPE_p_realm_value value, SWIGTYPE_p_bool out_found) {
    return realmcJNI.realm_dictionary_get(SWIGTYPE_p_realm_dictionary.getCPtr(arg0), SWIGTYPE_p_realm_value.getCPtr(key), SWIGTYPE_p_realm_value.getCPtr(value), SWIGTYPE_p_bool.getCPtr(out_found));
  }

  public static boolean realm_dictionary_find(SWIGTYPE_p_realm_dictionary arg0, SWIGTYPE_p_realm_value key, SWIGTYPE_p_realm_value out_value, SWIGTYPE_p_bool out_found) {
    return realmcJNI.realm_dictionary_find(SWIGTYPE_p_realm_dictionary.getCPtr(arg0), SWIGTYPE_p_realm_value.getCPtr(key), SWIGTYPE_p_realm_value.getCPtr(out_value), SWIGTYPE_p_bool.getCPtr(out_found));
  }

  public static boolean realm_dictionary_insert(SWIGTYPE_p_realm_dictionary arg0, SWIGTYPE_p_realm_value key, SWIGTYPE_p_realm_value value, SWIGTYPE_p_bool out_inserted, SWIGTYPE_p_size_t out_index) {
    return realmcJNI.realm_dictionary_insert(SWIGTYPE_p_realm_dictionary.getCPtr(arg0), SWIGTYPE_p_realm_value.getCPtr(key), SWIGTYPE_p_realm_value.getCPtr(value), SWIGTYPE_p_bool.getCPtr(out_inserted), SWIGTYPE_p_size_t.getCPtr(out_index));
  }

  public static boolean realm_dictionary_erase(SWIGTYPE_p_realm_dictionary arg0, SWIGTYPE_p_realm_value key, SWIGTYPE_p_bool out_erased) {
    return realmcJNI.realm_dictionary_erase(SWIGTYPE_p_realm_dictionary.getCPtr(arg0), SWIGTYPE_p_realm_value.getCPtr(key), SWIGTYPE_p_bool.getCPtr(out_erased));
  }

  public static boolean realm_dictionary_clear(SWIGTYPE_p_realm_dictionary arg0) {
    return realmcJNI.realm_dictionary_clear(SWIGTYPE_p_realm_dictionary.getCPtr(arg0));
  }

  public static boolean realm_dictionary_assign(SWIGTYPE_p_realm_dictionary arg0, SWIGTYPE_p_a_2__realm_value pairs, long num_pairs) {
    return realmcJNI.realm_dictionary_assign(SWIGTYPE_p_realm_dictionary.getCPtr(arg0), SWIGTYPE_p_a_2__realm_value.getCPtr(pairs), num_pairs);
  }

  public static SWIGTYPE_p_realm_query realm_query_new(SWIGTYPE_p_shared_realm arg0, SWIGTYPE_p_realm_table_key table) {
    long cPtr = realmcJNI.realm_query_new(SWIGTYPE_p_shared_realm.getCPtr(arg0), SWIGTYPE_p_realm_table_key.getCPtr(table));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_query(cPtr, false);
  }

  public static SWIGTYPE_p_realm_query realm_query_new_with_results(SWIGTYPE_p_realm_results arg0) {
    long cPtr = realmcJNI.realm_query_new_with_results(SWIGTYPE_p_realm_results.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_query(cPtr, false);
  }

  public static SWIGTYPE_p_realm_parsed_query realm_query_parse(SWIGTYPE_p_realm_string arg0) {
    long cPtr = realmcJNI.realm_query_parse(SWIGTYPE_p_realm_string.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_parsed_query(cPtr, false);
  }

  public static SWIGTYPE_p_realm_descriptor_ordering realm_new_descriptor_ordering() {
    long cPtr = realmcJNI.realm_new_descriptor_ordering();
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_descriptor_ordering(cPtr, false);
  }

  public static boolean realm_descriptor_ordering_append_sort(SWIGTYPE_p_realm_descriptor_ordering arg0, SWIGTYPE_p_void arg1) {
    return realmcJNI.realm_descriptor_ordering_append_sort(SWIGTYPE_p_realm_descriptor_ordering.getCPtr(arg0), SWIGTYPE_p_void.getCPtr(arg1));
  }

  public static boolean realm_descriptor_ordering_append_distinct(SWIGTYPE_p_realm_descriptor_ordering arg0, SWIGTYPE_p_realm_distinct_descriptor arg1) {
    return realmcJNI.realm_descriptor_ordering_append_distinct(SWIGTYPE_p_realm_descriptor_ordering.getCPtr(arg0), SWIGTYPE_p_realm_distinct_descriptor.getCPtr(arg1));
  }

  public static boolean realm_descriptor_ordering_append_limit(SWIGTYPE_p_realm_descriptor_ordering arg0, SWIGTYPE_p_realm_limit_descriptor arg1) {
    return realmcJNI.realm_descriptor_ordering_append_limit(SWIGTYPE_p_realm_descriptor_ordering.getCPtr(arg0), SWIGTYPE_p_realm_limit_descriptor.getCPtr(arg1));
  }

  public static boolean realm_descriptor_ordering_append_include(SWIGTYPE_p_realm_descriptor_ordering arg0, SWIGTYPE_p_realm_include_descriptor arg1) {
    return realmcJNI.realm_descriptor_ordering_append_include(SWIGTYPE_p_realm_descriptor_ordering.getCPtr(arg0), SWIGTYPE_p_realm_include_descriptor.getCPtr(arg1));
  }

  public static boolean realm_apply_parsed_predicate(SWIGTYPE_p_realm_query arg0, SWIGTYPE_p_realm_parsed_query arg1, SWIGTYPE_p_realm_parsed_query_arguments arg2, SWIGTYPE_p_realm_key_path_mapping arg3) {
    return realmcJNI.realm_apply_parsed_predicate(SWIGTYPE_p_realm_query.getCPtr(arg0), SWIGTYPE_p_realm_parsed_query.getCPtr(arg1), SWIGTYPE_p_realm_parsed_query_arguments.getCPtr(arg2), SWIGTYPE_p_realm_key_path_mapping.getCPtr(arg3));
  }

  public static boolean realm_apply_parsed_descriptor_ordering(SWIGTYPE_p_realm_descriptor_ordering arg0, SWIGTYPE_p_shared_realm arg1, SWIGTYPE_p_realm_table_key target, SWIGTYPE_p_realm_parsed_query arg3, SWIGTYPE_p_realm_key_path_mapping arg4) {
    return realmcJNI.realm_apply_parsed_descriptor_ordering(SWIGTYPE_p_realm_descriptor_ordering.getCPtr(arg0), SWIGTYPE_p_shared_realm.getCPtr(arg1), SWIGTYPE_p_realm_table_key.getCPtr(target), SWIGTYPE_p_realm_parsed_query.getCPtr(arg3), SWIGTYPE_p_realm_key_path_mapping.getCPtr(arg4));
  }

  public static boolean realm_query_count(SWIGTYPE_p_realm_query arg0, SWIGTYPE_p_size_t out_count) {
    return realmcJNI.realm_query_count(SWIGTYPE_p_realm_query.getCPtr(arg0), SWIGTYPE_p_size_t.getCPtr(out_count));
  }

  public static boolean realm_query_find_first(SWIGTYPE_p_realm_query arg0, SWIGTYPE_p_realm_obj_key out_key, SWIGTYPE_p_bool out_found) {
    return realmcJNI.realm_query_find_first(SWIGTYPE_p_realm_query.getCPtr(arg0), SWIGTYPE_p_realm_obj_key.getCPtr(out_key), SWIGTYPE_p_bool.getCPtr(out_found));
  }

  public static SWIGTYPE_p_realm_results realm_query_find_all(SWIGTYPE_p_realm_query arg0) {
    long cPtr = realmcJNI.realm_query_find_all(SWIGTYPE_p_realm_query.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_results(cPtr, false);
  }

  public static SWIGTYPE_p_realm_results realm_query_find_all_with_ordering(SWIGTYPE_p_realm_query arg0, SWIGTYPE_p_realm_descriptor_ordering arg1) {
    long cPtr = realmcJNI.realm_query_find_all_with_ordering(SWIGTYPE_p_realm_query.getCPtr(arg0), SWIGTYPE_p_realm_descriptor_ordering.getCPtr(arg1));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_results(cPtr, false);
  }

  public static boolean realm_query_delete_all(SWIGTYPE_p_realm_query arg0) {
    return realmcJNI.realm_query_delete_all(SWIGTYPE_p_realm_query.getCPtr(arg0));
  }

  public static boolean realm_query_min(SWIGTYPE_p_realm_query arg0, SWIGTYPE_p_realm_col_key arg1, SWIGTYPE_p_realm_value out_min) {
    return realmcJNI.realm_query_min(SWIGTYPE_p_realm_query.getCPtr(arg0), SWIGTYPE_p_realm_col_key.getCPtr(arg1), SWIGTYPE_p_realm_value.getCPtr(out_min));
  }

  public static boolean realm_query_max(SWIGTYPE_p_realm_query arg0, SWIGTYPE_p_realm_col_key arg1, SWIGTYPE_p_realm_value out_max) {
    return realmcJNI.realm_query_max(SWIGTYPE_p_realm_query.getCPtr(arg0), SWIGTYPE_p_realm_col_key.getCPtr(arg1), SWIGTYPE_p_realm_value.getCPtr(out_max));
  }

  public static boolean realm_query_sum(SWIGTYPE_p_realm_query arg0, SWIGTYPE_p_realm_col_key arg1, SWIGTYPE_p_realm_value out_sum) {
    return realmcJNI.realm_query_sum(SWIGTYPE_p_realm_query.getCPtr(arg0), SWIGTYPE_p_realm_col_key.getCPtr(arg1), SWIGTYPE_p_realm_value.getCPtr(out_sum));
  }

  public static boolean realm_query_average(SWIGTYPE_p_realm_query arg0, SWIGTYPE_p_realm_col_key arg1, SWIGTYPE_p_realm_value out_average) {
    return realmcJNI.realm_query_average(SWIGTYPE_p_realm_query.getCPtr(arg0), SWIGTYPE_p_realm_col_key.getCPtr(arg1), SWIGTYPE_p_realm_value.getCPtr(out_average));
  }

  public static boolean realm_query_push_op(SWIGTYPE_p_realm_query arg0, realm_query_op_e arg1) {
    return realmcJNI.realm_query_push_op(SWIGTYPE_p_realm_query.getCPtr(arg0), arg1.swigValue());
  }

  public static boolean realm_query_begin_group(SWIGTYPE_p_realm_query arg0) {
    return realmcJNI.realm_query_begin_group(SWIGTYPE_p_realm_query.getCPtr(arg0));
  }

  public static boolean realm_query_end_group(SWIGTYPE_p_realm_query arg0) {
    return realmcJNI.realm_query_end_group(SWIGTYPE_p_realm_query.getCPtr(arg0));
  }

  public static boolean realm_query_push_cond(SWIGTYPE_p_realm_query arg0, SWIGTYPE_p_realm_col_key arg1, realm_query_cond_e arg2, SWIGTYPE_p_realm_value values, long num_values, int flags) {
    return realmcJNI.realm_query_push_cond(SWIGTYPE_p_realm_query.getCPtr(arg0), SWIGTYPE_p_realm_col_key.getCPtr(arg1), arg2.swigValue(), SWIGTYPE_p_realm_value.getCPtr(values), num_values, flags);
  }

  public static boolean realm_query_push_cond_properties(SWIGTYPE_p_realm_query arg0, SWIGTYPE_p_realm_col_key lhs, realm_query_cond_e arg2, SWIGTYPE_p_realm_col_key rhs, int flags) {
    return realmcJNI.realm_query_push_cond_properties(SWIGTYPE_p_realm_query.getCPtr(arg0), SWIGTYPE_p_realm_col_key.getCPtr(lhs), arg2.swigValue(), SWIGTYPE_p_realm_col_key.getCPtr(rhs), flags);
  }

  public static boolean realm_query_push_query(SWIGTYPE_p_realm_query arg0, SWIGTYPE_p_realm_query arg1) {
    return realmcJNI.realm_query_push_query(SWIGTYPE_p_realm_query.getCPtr(arg0), SWIGTYPE_p_realm_query.getCPtr(arg1));
  }

  public static boolean realm_query_negate(SWIGTYPE_p_realm_query arg0) {
    return realmcJNI.realm_query_negate(SWIGTYPE_p_realm_query.getCPtr(arg0));
  }

  public static long realm_results_count(SWIGTYPE_p_realm_results arg0) {
    return realmcJNI.realm_results_count(SWIGTYPE_p_realm_results.getCPtr(arg0));
  }

  public static SWIGTYPE_p_realm_value realm_results_get(SWIGTYPE_p_realm_results arg0, long index) {
    return new SWIGTYPE_p_realm_value(realmcJNI.realm_results_get(SWIGTYPE_p_realm_results.getCPtr(arg0), index), true);
  }

  public static boolean realm_results_delete_all(SWIGTYPE_p_realm_results arg0) {
    return realmcJNI.realm_results_delete_all(SWIGTYPE_p_realm_results.getCPtr(arg0));
  }

  public static boolean realm_results_filter(SWIGTYPE_p_realm_results arg0, SWIGTYPE_p_realm_query arg1) {
    return realmcJNI.realm_results_filter(SWIGTYPE_p_realm_results.getCPtr(arg0), SWIGTYPE_p_realm_query.getCPtr(arg1));
  }

  public static boolean realm_results_sort(SWIGTYPE_p_realm_results arg0, SWIGTYPE_p_realm_sort_descriptor arg1) {
    return realmcJNI.realm_results_sort(SWIGTYPE_p_realm_results.getCPtr(arg0), SWIGTYPE_p_realm_sort_descriptor.getCPtr(arg1));
  }

  public static boolean realm_results_distinct(SWIGTYPE_p_realm_results arg0, SWIGTYPE_p_realm_distinct_descriptor arg1) {
    return realmcJNI.realm_results_distinct(SWIGTYPE_p_realm_results.getCPtr(arg0), SWIGTYPE_p_realm_distinct_descriptor.getCPtr(arg1));
  }

  public static boolean realm_results_limit(SWIGTYPE_p_realm_results arg0, SWIGTYPE_p_realm_limit_descriptor arg1) {
    return realmcJNI.realm_results_limit(SWIGTYPE_p_realm_results.getCPtr(arg0), SWIGTYPE_p_realm_limit_descriptor.getCPtr(arg1));
  }

  public static boolean realm_results_apply_ordering(SWIGTYPE_p_realm_results arg0, SWIGTYPE_p_realm_descriptor_ordering arg1) {
    return realmcJNI.realm_results_apply_ordering(SWIGTYPE_p_realm_results.getCPtr(arg0), SWIGTYPE_p_realm_descriptor_ordering.getCPtr(arg1));
  }

  public static SWIGTYPE_p_realm_results realm_results_snapshot(SWIGTYPE_p_realm_results arg0) {
    long cPtr = realmcJNI.realm_results_snapshot(SWIGTYPE_p_realm_results.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_results(cPtr, false);
  }

  public static SWIGTYPE_p_realm_results realm_results_freeze(SWIGTYPE_p_realm_results arg0, SWIGTYPE_p_shared_realm frozen_realm) {
    long cPtr = realmcJNI.realm_results_freeze(SWIGTYPE_p_realm_results.getCPtr(arg0), SWIGTYPE_p_shared_realm.getCPtr(frozen_realm));
    return (cPtr == 0) ? null : new SWIGTYPE_p_realm_results(cPtr, false);
  }

  public static boolean realm_results_min(SWIGTYPE_p_realm_results arg0, SWIGTYPE_p_realm_col_key arg1, SWIGTYPE_p_realm_value out_min) {
    return realmcJNI.realm_results_min(SWIGTYPE_p_realm_results.getCPtr(arg0), SWIGTYPE_p_realm_col_key.getCPtr(arg1), SWIGTYPE_p_realm_value.getCPtr(out_min));
  }

  public static boolean realm_results_max(SWIGTYPE_p_realm_results arg0, SWIGTYPE_p_realm_col_key arg1, SWIGTYPE_p_realm_value out_max) {
    return realmcJNI.realm_results_max(SWIGTYPE_p_realm_results.getCPtr(arg0), SWIGTYPE_p_realm_col_key.getCPtr(arg1), SWIGTYPE_p_realm_value.getCPtr(out_max));
  }

  public static boolean realm_results_sum(SWIGTYPE_p_realm_results arg0, SWIGTYPE_p_realm_col_key arg1, SWIGTYPE_p_realm_value out_sum) {
    return realmcJNI.realm_results_sum(SWIGTYPE_p_realm_results.getCPtr(arg0), SWIGTYPE_p_realm_col_key.getCPtr(arg1), SWIGTYPE_p_realm_value.getCPtr(out_sum));
  }

  public static boolean realm_results_average(SWIGTYPE_p_realm_results arg0, SWIGTYPE_p_realm_col_key arg1, SWIGTYPE_p_realm_value out_average) {
    return realmcJNI.realm_results_average(SWIGTYPE_p_realm_results.getCPtr(arg0), SWIGTYPE_p_realm_col_key.getCPtr(arg1), SWIGTYPE_p_realm_value.getCPtr(out_average));
  }

}
