/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class realm_collection_type_e {
  public final static realm_collection_type_e RLM_COLLECTION_TYPE_NONE = new realm_collection_type_e("RLM_COLLECTION_TYPE_NONE", realmcJNI.RLM_COLLECTION_TYPE_NONE_get());
  public final static realm_collection_type_e RLM_COLLECTION_TYPE_LIST = new realm_collection_type_e("RLM_COLLECTION_TYPE_LIST", realmcJNI.RLM_COLLECTION_TYPE_LIST_get());
  public final static realm_collection_type_e RLM_COLLECTION_TYPE_SET = new realm_collection_type_e("RLM_COLLECTION_TYPE_SET", realmcJNI.RLM_COLLECTION_TYPE_SET_get());
  public final static realm_collection_type_e RLM_COLLECTION_TYPE_DICTIONARY = new realm_collection_type_e("RLM_COLLECTION_TYPE_DICTIONARY", realmcJNI.RLM_COLLECTION_TYPE_DICTIONARY_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static realm_collection_type_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + realm_collection_type_e.class + " with value " + swigValue);
  }

  private realm_collection_type_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private realm_collection_type_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private realm_collection_type_e(String swigName, realm_collection_type_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static realm_collection_type_e[] swigValues = { RLM_COLLECTION_TYPE_NONE, RLM_COLLECTION_TYPE_LIST, RLM_COLLECTION_TYPE_SET, RLM_COLLECTION_TYPE_DICTIONARY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

