/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class realm_logic_error_kind_e {
  public final static realm_logic_error_kind_e RLM_LOGIC_ERR_NONE = new realm_logic_error_kind_e("RLM_LOGIC_ERR_NONE", realmcJNI.RLM_LOGIC_ERR_NONE_get());
  public final static realm_logic_error_kind_e RLM_LOGIC_ERR_STRING_TOO_BIG = new realm_logic_error_kind_e("RLM_LOGIC_ERR_STRING_TOO_BIG");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static realm_logic_error_kind_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + realm_logic_error_kind_e.class + " with value " + swigValue);
  }

  private realm_logic_error_kind_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private realm_logic_error_kind_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private realm_logic_error_kind_e(String swigName, realm_logic_error_kind_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static realm_logic_error_kind_e[] swigValues = { RLM_LOGIC_ERR_NONE, RLM_LOGIC_ERR_STRING_TOO_BIG };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

