/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class realm_column_attr_e {
  public final static realm_column_attr_e RLM_COLUMN_ATTR_NONE = new realm_column_attr_e("RLM_COLUMN_ATTR_NONE", realmcJNI.RLM_COLUMN_ATTR_NONE_get());
  public final static realm_column_attr_e RLM_COLUMN_ATTR_INDEXED = new realm_column_attr_e("RLM_COLUMN_ATTR_INDEXED", realmcJNI.RLM_COLUMN_ATTR_INDEXED_get());
  public final static realm_column_attr_e RLM_COLUMN_ATTR_UNIQUE = new realm_column_attr_e("RLM_COLUMN_ATTR_UNIQUE", realmcJNI.RLM_COLUMN_ATTR_UNIQUE_get());
  public final static realm_column_attr_e RLM_COLUMN_ATTR_RESERVED = new realm_column_attr_e("RLM_COLUMN_ATTR_RESERVED", realmcJNI.RLM_COLUMN_ATTR_RESERVED_get());
  public final static realm_column_attr_e RLM_COLUMN_ATTR_STRONG_LINKS = new realm_column_attr_e("RLM_COLUMN_ATTR_STRONG_LINKS", realmcJNI.RLM_COLUMN_ATTR_STRONG_LINKS_get());
  public final static realm_column_attr_e RLM_COLUMN_ATTR_NULLABLE = new realm_column_attr_e("RLM_COLUMN_ATTR_NULLABLE", realmcJNI.RLM_COLUMN_ATTR_NULLABLE_get());
  public final static realm_column_attr_e RLM_COLUMN_ATTR_LIST = new realm_column_attr_e("RLM_COLUMN_ATTR_LIST", realmcJNI.RLM_COLUMN_ATTR_LIST_get());
  public final static realm_column_attr_e RLM_COLUMN_ATTR_DICTIONARY = new realm_column_attr_e("RLM_COLUMN_ATTR_DICTIONARY", realmcJNI.RLM_COLUMN_ATTR_DICTIONARY_get());
  public final static realm_column_attr_e RLM_COLUMN_ATTR_COLLECTION = new realm_column_attr_e("RLM_COLUMN_ATTR_COLLECTION", realmcJNI.RLM_COLUMN_ATTR_COLLECTION_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static realm_column_attr_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + realm_column_attr_e.class + " with value " + swigValue);
  }

  private realm_column_attr_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private realm_column_attr_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private realm_column_attr_e(String swigName, realm_column_attr_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static realm_column_attr_e[] swigValues = { RLM_COLUMN_ATTR_NONE, RLM_COLUMN_ATTR_INDEXED, RLM_COLUMN_ATTR_UNIQUE, RLM_COLUMN_ATTR_RESERVED, RLM_COLUMN_ATTR_STRONG_LINKS, RLM_COLUMN_ATTR_NULLABLE, RLM_COLUMN_ATTR_LIST, RLM_COLUMN_ATTR_DICTIONARY, RLM_COLUMN_ATTR_COLLECTION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

