/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SWIGTYPE_p_realm_sync_config {
  private transient long swigCPtr;

  protected SWIGTYPE_p_realm_sync_config(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_realm_sync_config() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_realm_sync_config obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

