/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SWIGTYPE_p_f_p_void_p_struct_shared_realm_p_struct_shared_realm_p_q_const__struct_realm_schema__void {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_p_void_p_struct_shared_realm_p_struct_shared_realm_p_q_const__struct_realm_schema__void(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_void_p_struct_shared_realm_p_struct_shared_realm_p_q_const__struct_realm_schema__void() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_void_p_struct_shared_realm_p_struct_shared_realm_p_q_const__struct_realm_schema__void obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

