/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SWIGTYPE_p_f_p_void_uint64_t_uint64_t__bool {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_p_void_uint64_t_uint64_t__bool(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_void_uint64_t_uint64_t__bool() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_void_uint64_t_uint64_t__bool obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

