name: PR Build
on:
  workflow_dispatch:  # Add this line to enable manual triggering
  pull_request:
    paths-ignore:
    - '**.md'

env:
  REALM_DISABLE_ANALYTICS: true
  CMAKE_C_COMPILER: /usr/local/opt/ccache/libexec/clang
  CMAKE_CXX_COMPILER: /usr/local/opt/ccache/libexec/clang++
  RELEASE_BRANCHES: "[ 'master', 'releases', 'feature/github-actions' ]"

jobs:
  static-analysis:
    uses: ./.github/workflows/include-static-analysis.yml
   
  check-cache:
    uses: ./.github/workflows/include-check-cache.yml
